## Synthetic population pipeline for Rennes
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the output population in the output_path (see below)
  # - matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 4

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: emc²_35

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.001
  random_seed: 1234
  
  # Paths to the input data and where the output should be stored
  data_path: /home/valentin/data/EQASIM/data
  output_path: /home/valentin/data/EQASIM/output
  output_prefix: rennes_0.001_

  # Only interesting if you run the simulation
  java_memory: 14G

  # Rennes settings
  census_path: rp_2015/FD_INDCVIZC_2015.dbf
  regions: []
  departments: [35]
